version: "3"
services:
  test:
    build: .
    ports:
      - "4100:4100"
    container_name: gfw-area-test
    environment:
      NODE_ENV: test
      PORT: 4110
      NODE_PATH: app/src
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: cttoken
      LOCAL_URL: http://127.0.0.1:4110
      HOST_IP: 127.0.0.1
      MONGO_PORT_27017_TCP_ADDR: mongo
      S3_ACCESS_KEY_ID: 1
      S3_SECRET_ACCESS_KEY: 1
      S3_BUCKET: s3bucket
      WAIT_HOSTS: mongo:27017
      FASTLY_ENABLED: "false"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    command: test
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
    ports:
      - "27017"
