version: "3"
services:
  develop:
    build: .
    ports:
      - "4200:4100"
    container_name: gfw-area
    env_file:
      - dev.env.sample
    environment:
      PORT: 4100
      NODE_ENV: dev
      NODE_PATH: app/src
      API_VERSION: v1
      CT_REGISTER_MODE: auto
      MONGO_PORT_27017_TCP_ADDR: mongo
      WAIT_HOSTS: mongo:27017
      DEFORESTATION_ALERTS_DATASET_ID: 4145f642-5455-4414-b214-58ad39b83e1e
      FIRE_ALERTS_DATASET_ID: 63e88e53-0a88-416e-9532-fa06f703d435
      MONTHLY_SUMMARY_DATASET_ID: monthlySummary
    command: develop
    depends_on:
      - mongo
    volumes:
      - ./app:/opt/gfw-area/app
  mongo:
    image: mongo:3.4
    container_name: gfw-areas-mongo
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      - $HOME/docker/data/gfw-area-api:/data/db
    restart: always
