version: "3"
services:
  develop:
    build: .
    ports:
      - "4200:4100"
    container_name: gfw-area
    env_file:
      - dev.env
    environment:
      PORT: 4100
      NODE_ENV: dev
      NODE_PATH: app/src
      MONGO_PORT_27017_TCP_ADDR: mongo
      WAIT_HOSTS: mongo:27017
      FASTLY_ENABLED: "false"
    command: develop
    depends_on:
      - mongo
    volumes:
      - ./app:/opt/gfw-area/app
  mongo:
    image: mongo:3.4
    container_name: gfw-areas-mongo
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      - $HOME/docker/data/gfw-area-api:/data/db
    restart: always
