test:
  extends:
    file: base.yml
    service: base
  ports:
    - "4100"
  container_name: gfw-area-test
  environment:
    NODE_ENV: test
    CT_URL: http://mymachine:9000
    API_VERSION: v1
    S3_ACCESS_KEY_ID: 1
    S3_SECRET_ACCESS_KEY: 1
    S3_BUCKET: s3bucket
  command: test
