test:
  extends:
    file: base.yml
    service: base
  ports:
    - "4100"
  container_name: gfw-area-test
  environment:
    NODE_ENV: test
    CT_URL: http://mymachine:9000
    API_VERSION: v1
  command: test
