apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: gfw
  name: area
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: area
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
